# Generated by Django 3.0.2 on 2020-01-05 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
                ('birthreg', models.CharField(max_length=100, unique=True)),
                ('religion', models.CharField(max_length=100)),
                ('Fathername', models.CharField(max_length=100)),
                ('Mothername', models.CharField(max_length=100)),
                ('Present_addr', models.CharField(max_length=1000)),
                ('Permanent_addr', models.CharField(max_length=1000)),
                ('contact_no', models.CharField(max_length=11)),
                ('belongs_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
