# Generated by Django 3.0.2 on 2020-01-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_applicant_new_admission_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_new',
            name='birthreg',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
